server:
  port: 8080
  

---
spring:
  application:
    name: springdoc
  pid:
    file: /data1/springboot/springdoc.pid
---
logging:
  config: classpath:logback-local.xml

springdoc:
  swagger-ui:
    operations-sorter: alpha 	# alpha(알파벳 오름차순), method(HTTP메소드순)
    tags-sorter: alpha 			# 태그 정렬 기준
    path: /swagger-ui.html 		# html 문서 접속 경로
    disable-swagger-default-url: true
    doc-expansion: none 		# tag, operation 펼치는 방식
#  paths-to-match:
#    - /**						# swagger에서 사용할 URL 패턴을 지정
